### ISSUE TITLE
Player not working on Safari

### ISSUE THREAD

**Issue by simon-tannai** [GoogleWebComponents/google-youtube#89]
Hello ! 

I'm trying to use this component on Safari, version 12.0.2 on MacOS 10.14.2. 
The `<google-youtube>` is present into HTML DOM but nothing is displayed on the webapp. I have not any error into the JavaScript console.
On Google Chrome, it's working fine.

The full html:
```html
<link rel="import" href="bower_components/google-youtube/google-youtube.html">
<google-youtube class="googleYouTube" video-id="l_BWeuz1k4c"></google-youtube>
```

CSS:
```css
.googleYouTube {
  display: block;
  width: 480px;
  margin: 0 auto;
  height: 270px;
}
```

There is specs to apply to be able to work on Safari brower ?
